# Generated by Django 3.1.5 on 2021-01-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankdetails', '0002_auto_20210119_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='favourite',
            field=models.BooleanField(default=False),
        ),
    ]
